framework:
    cache:
        app: cache.adapter.memcached
        default_memcached_provider: 'memcached://%env(MEMCACHED_HOST)%:%env(MEMCACHED_PORT)%'
        prefix_seed: '%env(MEMCACHED_PREFIX)%'
