### create Rozetka account
POST {{endpoint}}/v1/rozetka/account/create
Content-Type: application/json

{
  "username": "username",
  "encoded_password": "encoded_password"
}

### find Rozetka account
POST {{endpoint}}/v1/rozetka/account/find
access-token: {{access-token}}
Content-Type: application/json

{
  "username": "find_this_username"
}