rozetka_account_create:
  path: /rozetka/account/create
  controller: App\PrivateApi\Controller\Rozetka\Account\Create\Handler::process
  methods: POST

rozetka_account_find:
  path: /rozetka/account/find
  controller: App\PrivateApi\Controller\Rozetka\Account\Find\Handler::process
  methods: POST