parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
  App\:
    resource: '../src/'
    exclude:
      - '../src/Kernel.php'

  App\ThirdParty\Amazon\Sqs\MessageResolver:
    public: true
    arguments: [ !tagged_iterator { tag: 'app.amazon.sqs.message.factory' } ]

  App\Kernel\FileStorage\EngineInterface:
    factory: [ '@App\Kernel\FileStorage\EngineFactory', 'create' ]
  App\Kernel\FileStorage\EngineFactory:
    arguments:
      $engine: '%env(FILE_STORAGE_ENGINE)%'
      $googleAppKeyfile: '%env(GOOGLE_APPLICATION_CREDENTIALS)%'
      $googleStorageBucket: '%env(GOOGLE_STORAGE_BUCKET)%'

  App\Kernel\FoldersStructure:
    arguments:
      $projectDir: '%kernel.project_dir%'
