FROM php:fpm

RUN apt-get update && \
    apt-get upgrade -y

RUN apt-get install -y git \
    && git config --global user.email "tarpedo10@gmail.com" \
    && git config --global user.name "Oleksandr D."

RUN apt-get install -y mc

RUN apt-get install -y \
    libzip-dev \
    libxslt1-dev \
    libpng-dev \
    libonig-dev

RUN docker-php-ext-install \
    pdo pdo_mysql zip xsl gd intl opcache exif mbstring

RUN docker-php-ext-configure pcntl --enable-pcntl \
  && docker-php-ext-install \
    pcntl

RUN curl -sSL https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions -o - | sh -s \
      php-memcached-dev/php-memcached@v3.2.0RC2