FROM php:fpm

RUN apt-get update && \
    apt-get upgrade -y

RUN apt-get install -y git \
    && git config --global user.email "tarpedo10@gmail.com" \
    && git config --global user.name "Oleksandr D."

RUN apt-get install -y mc

RUN apt-get install -y \
    libzip-dev \
    libxslt1-dev \
    libpng-dev \
    libonig-dev

RUN docker-php-ext-install \
    pdo pdo_mysql zip xsl gd intl opcache exif mbstring

RUN docker-php-ext-configure pcntl --enable-pcntl \
  && docker-php-ext-install \
    pcntl

RUN cd /tmp && git clone https://github.com/websupport-sk/pecl-memcache && \
     cd pecl-memcache && \
     phpize && \
     ./configure && \
     make && \
     make install && \
     docker-php-ext-enable memcache