version: "3.9"

networks:
  rozetka_gateway_net:

services:
  memcached:
    image: memcached:1.6.21-alpine
    networks:
      - rozetka_gateway_net
  cron:
    build:
      dockerfile: php/Dockerfile-cron
    working_dir: /var/www
    volumes:
      - ../../:/var/www
    tty: true
    command: php bin/console messenger:consume -vv scheduler_cron
    networks:
      - rozetka_gateway_net
  server:
    build:
      dockerfile: php/Dockerfile
    ports:
      - "${APP_HTTP_PORT}:80"
      - "${APP_HTTPS_PORT}:443"
    working_dir: /var/www
    volumes:
      - ../../:/var/www
    tty: true
    command: >
      sh -c "
      service apache2 start
      && ./wait
      && composer install --no-interaction
      && php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
      && sleep infinity"
    environment:
      WAIT_HOSTS: db:3306
      WAIT_HOSTS_TIMEOUT: 1000
    networks:
      - rozetka_gateway_net
  db:
    image:
      mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: rozetka_gateway
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${APP_MYSQL_PORT}:3306"
    networks:
      - rozetka_gateway_net
volumes:
  db_data:
